version: '3'

services:
  shop-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: shop-api
    env_file:
      - .env
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    environment:
      # Only for development purporses 
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 3306:3306
